### ISSUE TITLE
Strange mappings for `i`, `I`, `a`, `A`

### ISSUE THREAD

**Issue by huyz** [vipzhicheng/logseq-plugin-vim-shortcuts#20]
Why are there such weird mappings for `i`, `I`, `a`, and there's no `A`?

If I could use either:
- `i` and `a` to go to the beginning and to the end, respectively; or
- `I` and `A`

I would be happy.  As that would be consistent with vim.

But I'm forced to use `I` and `a`--one uppercase and one lowercase which makes it harder to remember.

Is there a way to change these mappings?

**Comment by vipzhicheng** [comment]
You can change settings on plugin page, then click the left bottom dropdown menu to go to the settings file.

![image](https://user-images.githubusercontent.com/1209538/179216461-a0a82ae0-d38e-48f1-a8f1-045be8543618.png)


Yes you are right, I will add `A` to do the same as `a`

Actually `a` and `i` in Vim is different from Logseq, because Logseq do not have cursor for now.

**Comment by vipzhicheng** [comment]
Please upgrade to v0.1.11.

**Comment by huyz** [comment]
Thanks!

I would still argue the default `i` is incorrect and is very counterintuitive (to me when a whole block is selected, it acts a cursor, and thus `i` should insert at the beginning of the selection), but this is good enough for me :)

**Comment by vipzhicheng** [comment]
Yes, in the new release, I have changed `i` to insert at the beginning.
