### ISSUE TITLE
command mode not working

### ISSUE THREAD

**Issue by tiankonganddahai** [vipzhicheng/logseq-plugin-vim-shortcuts#8]
Thanks a lot for build a so good tool.
When i use `mod+shift+; `，but it has no response，I don't know why? can give some advice.

**Comment by vipzhicheng** [comment]
Two possibilities:

1.`mod` means `ctrl`  on Windows and `cmd` on Mac.
2. Logseq window must be focused.

**Comment by plasticboy** [comment]
I have the same issue on Linux. The `ctrl+shift+;` shortcut doesn't work. I'm only able to get the command prompt to come up by opening the command palette with `ctrl+shift+p` and searching for "Call VIM commands".

**Comment by tiankonganddahai** [comment]
> Two possibilities:
> 
> 1.`mod` means `ctrl` on Windows and `cmd` on Mac. 2. Logseq window must be focused.

Yes, i use `ctrl+shift+;`, and none response

**Comment by vipzhicheng** [comment]
Please upgrade to latest version, in that version I added a new trigger: `ctrl+alt+;`

I can reproduce this issue on WIndows but can not make it work, I think there is something wrong on WIndows key-binding, that's why I added a new one.

Please give it a try to see if it works for you.

By the way, the `Y`, `zo`, and `zm` work for me on Windows.

**Comment by plasticboy** [comment]
Awesome, thanks. `ctrl+alt+;` is working for me on Linux with version 0.1.3.
